/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Filters: typeof import('./components/x-table/filters/index.vue')['default']
    Item: typeof import('./components/x-table/filters/item.vue')['default']
    Pagination: typeof import('./components/x-table/pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableData: typeof import('./components/x-table/table-data/index.vue')['default']
    XContent: typeof import('./components/x-content/index.vue')['default']
    XOperate: typeof import('./components/x-operate/index.vue')['default']
    XStatus: typeof import('./components/x-status/index.vue')['default']
    XSvg: typeof import('./components/x-svg/index.vue')['default']
    XTable: typeof import('./components/x-table/index.vue')['default']
  }
}
